export const SELECT_INSTRUMENT = 'SELECT_INSTRUMENT'
export const INSTRUMENT_NAME = 'INSTRUMENT_NAME'

export const SET_TEMPO = 'SET_TEMPO'

// Sequencer
export const SEQUENCE_SET_SIZE = 'SEQUENCE_SET_SIZE'
export const SEQUENCE_UPDATE = 'SEQUENCE_UPDATE'
export const SET_SEQUENCE_VALUE = 'SET_SEQUENCE_VALUE'
export const SET_SEQUENCE_VALUES = 'SET_SEQUENCE_VALUES'
export const TRANSFORM_SEQUENCE_VALUES = 'TRANSFORM_SEQUENCE_VALUES'
